// <auto-generated />
using Dividas.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dividas.WebApi.Migrations
{
    [DbContext(typeof(DividaContext))]
    partial class DividaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Dividas.WebApi.Model.Divida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataCompra");

                    b.Property<int>("FormaPagamento");

                    b.Property<string>("Titulo");

                    b.Property<double>("Valor");

                    b.Property<string>("Vencimento");

                    b.HasKey("Id");

                    b.ToTable("Dividas");
                });
#pragma warning restore 612, 618
        }
    }
}
